%\begin{tabular}{llr}
vergangen & Woche & 14 \\
 & Jahr & 8 \\
öffentlich-rechtlich & Rundfunk & 7 \\
norddeutsch & Landesbank & 6 \\
grün & Gentechnik & 5 \\
rein & Spekulation & 5 \\
liberaldemokratisch & Partei & 4 \\
klug & Entscheidung & 4 \\
offen & Denkmal & 4 \\
früh & Außenminister & 4 \\
% dritt%  & Wahlgang%  & 4 \\% neu%  & Variante%  & 4 \\% nah%  & Jahr%  & 4 \\% groß%  & Koalition%  & 4 \\
%\end{tabular}
